name: Yarn CI for Grafana plugins

on:
  push:
    paths:
      - 'grafana-monitoring/**'
      - '.github/workflows/yarn-grafana-plugins.yml'
    branches:
      - 'feature/**'
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

env:
  REGISTRY_USER: ${{ secrets.CS_ARTIFACTORY_USER }}
  REGISTRY_PWD: ${{ secrets.CS_ARTIFACTORY_PASSWORD }}
  REGISTRY_BASE: artifactory.coprs.esa-copernicus.eu
  REGISTRY_PROJECT: rs-zip

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [invalidations-completeness, invalidations-timeliness]

    steps:
      - uses: actions/checkout@v3

      - name: Set zip name 
        run: |
          ZIP_NAME="${{ matrix.component }}.zip"
          echo "ZIP_NAME=${ZIP_NAME}" >> $GITHUB_ENV

      - name: Set zip name for tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          # TAG
          GIT_TAG=${GITHUB_REF/refs\/tags\//}
          echo "GIT_TAG=${GIT_TAG}" >> $GITHUB_ENV
          # ZIP Name
          ZIP_NAME="${{ matrix.component }}_${GIT_TAG}.zip"
          echo "ZIP_NAME=${ZIP_NAME}" >> $GITHUB_ENV

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '17.3.0'
          cache: 'yarn'
          cache-dependency-path: 'grafana-monitoring/grafana/plugins/${{ matrix.component }}'

      - name: Build grafana plugin
        run: |
          cd grafana-monitoring/grafana/plugins/${{ matrix.component }}
          yarn cache clean && yarn install && yarn cache clean && yarn add @grafana/toolkit@9.0.2 && yarn build

      - name: Remove node_modules
        run: |
          cd grafana-monitoring/grafana/plugins/${{ matrix.component }}
          rm -rf node_modules
      
      - name: Zip plugin
        run: |
          cd grafana-monitoring/grafana/plugins
          zip -qq -r ${ZIP_NAME} ${{ matrix.component }}

      - name: Compute checksum
        run: |
          cd grafana-monitoring/grafana/plugins
          ARTIFACT_MD5_CHECKSUM=$(md5sum ${ZIP_NAME} | awk '{print $1}')
          ARTIFACT_SHA1_CHECKSUM=$(shasum -a 1 ${ZIP_NAME} | awk '{ print $1 }')
          ARTIFACT_SHA256_CHECKSUM=$(shasum -a 256 ${ZIP_NAME} | awk '{ print $1 }')
          echo "ARTIFACT_MD5_CHECKSUM=$ARTIFACT_MD5_CHECKSUM" >> $GITHUB_ENV
          echo "ARTIFACT_SHA1_CHECKSUM=$ARTIFACT_SHA1_CHECKSUM" >> $GITHUB_ENV
          echo "ARTIFACT_SHA256_CHECKSUM=$ARTIFACT_SHA256_CHECKSUM" >> $GITHUB_ENV
      
      - name: Upload zipped plugin in Artifactory
        run: |
          cd grafana-monitoring/grafana/plugins
          curl --header "X-Checksum-MD5:${ARTIFACT_MD5_CHECKSUM}" \
               --header "X-Checksum-Sha1:${ARTIFACT_SHA1_CHECKSUM}" \
               --header "X-Checksum-Sha256:${ARTIFACT_SHA256_CHECKSUM}" \
               -u "${REGISTRY_USER}:${REGISTRY_PWD}" \
               -T "${ZIP_NAME}" \
               -X PUT "https://${REGISTRY_BASE}/artifactory/${REGISTRY_PROJECT}/monitoring/${ZIP_NAME}"